tide:
  queries:
  - labels:
    - approved
    - lgtm
    missingLabels:
    - backports/unvalidated-commits
    - bugzilla/invalid-bug
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - jira/invalid-bug
    - needs-ok-to-test
    - needs-rebase
    repos:
    - trustyai-explainability/trustyai-explainability
